# Generated by Django 6.0 on 2026-01-07 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('claude_critique', models.TextField(blank=True)),
                ('gpt_critique', models.TextField(blank=True)),
                ('gemini_critique', models.TextField(blank=True)),
                ('orwellian_clarity_score', models.DecimalField(blank=True, decimal_places=1, help_text='Concrete language, active voice, sentence variety (0-100)', max_digits=5, null=True)),
                ('hitchensian_fire_score', models.DecimalField(blank=True, decimal_places=1, help_text='Argument structure, wit, intellectual honesty (0-100)', max_digits=5, null=True)),
                ('vivid_physicality_score', models.DecimalField(blank=True, decimal_places=1, help_text='Sensory language, metaphor coherence (0-100)', max_digits=5, null=True)),
                ('technical_execution_score', models.DecimalField(blank=True, decimal_places=1, help_text='Grammar, redundancies, flow (0-100)', max_digits=5, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=1, help_text='Weighted average: Clarity 40%, Fire 30%, Physicality 20%, Technical 10%', max_digits=5, null=True)),
                ('historical_avg_score', models.DecimalField(blank=True, decimal_places=1, help_text='Average score computed from top published pieces', max_digits=5, null=True)),
                ('abstract_nouns', models.JSONField(blank=True, default=list, help_text='Flagged abstract words: situation, aspect, factor, etc.', null=True)),
                ('passive_voice_sentences', models.JSONField(blank=True, default=list, help_text='Sentence indices with passive voice', null=True)),
                ('jargon_violations', models.JSONField(blank=True, default=dict, help_text='Detected jargon/euphemisms with suggested replacements', null=True)),
                ('weak_verbs', models.JSONField(blank=True, default=list, help_text='Weak verb instances flagged for replacement', null=True)),
                ('rhetorical_highlights', models.JSONField(blank=True, default=list, help_text='Strong rhetorical devices detected', null=True)),
                ('consensus_verdict', models.CharField(blank=True, choices=[('PROCESSING', 'Processing'), ('PUBLISH', 'Ready to Publish'), ('REVISE', 'Requires Revision'), ('REWRITE', 'Structural Rewrite Needed')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishedPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('published_date', models.DateField()),
                ('publication', models.CharField(blank=True, max_length=200)),
                ('social_shares', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('citation_count', models.IntegerField(default=0, help_text='Times cited or referenced by others')),
                ('clarity_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Your retrospective Orwellian clarity score (1-10)', null=True)),
                ('impact_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Your retrospective impact/persuasiveness score (1-10)', null=True)),
                ('notes', models.TextField(blank=True, help_text='What worked, what failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='SuggestedRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_source', models.CharField(choices=[('claude', 'Claude'), ('gpt', 'GPT'), ('gemini', 'Gemini')], max_length=20)),
                ('original_text', models.TextField(help_text='The problematic passage')),
                ('suggested_text', models.TextField(help_text='The improved version')),
                ('issue_type', models.CharField(help_text="e.g., 'passive_voice', 'abstract_noun', 'weak_verb', 'jargon'", max_length=50)),
                ('explanation', models.TextField(help_text='Why this change improves the writing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='orwell_hitchens.draftevaluation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WriterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_context', models.CharField(help_text="e.g., 'Foreign Policy Analyst', 'Political Commentator'", max_length=200)),
                ('writing_domains', models.TextField(help_text='Your areas of expertise (for calibration and context)')),
                ('style_preferences', models.TextField(default='1. Concrete over abstract (Orwell)\n2. Every sentence advances an argument (Hitchens)\n3. Anglo-Saxon words over Latinate\n4. Active voice carries conviction', help_text='Your non-negotiable writing principles')),
                ('target_publications', models.CharField(default='The Atlantic, Foreign Affairs, The New Yorker', help_text='Target publications/platforms for calibration', max_length=300)),
                ('forbidden_jargon', models.TextField(default='synergy, leverage, robust, stakeholder, impact (as verb), utilize, facilitate, optimize', help_text='Comma-separated bureaucratic euphemisms to avoid')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='draftevaluation',
            index=models.Index(fields=['user', 'submitted_at'], name='orwell_hitc_user_id_3552b1_idx'),
        ),
        migrations.AddIndex(
            model_name='draftevaluation',
            index=models.Index(fields=['submitted_at'], name='orwell_hitc_submitt_0a040f_idx'),
        ),
    ]
