# Generated by Django 6.0 on 2026-01-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orwell_hitchens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftevaluation',
            name='before_after_examples',
            field=models.JSONField(blank=True, default=list, help_text='Before/after rewrites showing improvements', null=True),
        ),
        migrations.AddField(
            model_name='draftevaluation',
            name='concrete_next_steps',
            field=models.JSONField(blank=True, default=list, help_text='Specific actionable improvements for next draft', null=True),
        ),
        migrations.AddField(
            model_name='draftevaluation',
            name='diagnostic_summary',
            field=models.TextField(blank=True, help_text='Core weaknesses identified with examples'),
        ),
        migrations.AddField(
            model_name='draftevaluation',
            name='one_sentence_verdict',
            field=models.TextField(blank=True, help_text='Concise summary of overall assessment'),
        ),
        migrations.AddField(
            model_name='draftevaluation',
            name='recurring_patterns',
            field=models.JSONField(blank=True, default=list, help_text='Habits and tendencies detected across the draft', null=True),
        ),
        migrations.AddField(
            model_name='draftevaluation',
            name='strengths_to_amplify',
            field=models.JSONField(blank=True, default=list, help_text='Things the writer is doing RIGHT to double down on', null=True),
        ),
    ]
