#!/bin/bash

# Check if project name is provided
if [ $# -eq 0 ]; then
    echo "Usage: ./scripts/setup_project.sh <project_name>"
    exit 1
fi

PROJECT_NAME=$1
TEMPLATE_NAME="sovereigncritic"
CURRENT_DIR=$(pwd)

echo "Setting up new Django project: $PROJECT_NAME"

# 1. Create project directory
mkdir -p ../$PROJECT_NAME
cp -r ./* ../$PROJECT_NAME/
cd ../$PROJECT_NAME

# Remove the original db.sqlite3 file
rm -f db.sqlite3

# 2. Generate new secret keys
SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(50))")

# 3. Create new .env file
cat > .env << EOL
# Security
SECRET_KEY=$SECRET_KEY
DEBUG=True

# Database
DB_NAME=$PROJECT_NAME
DB_USER=postgres
DB_PASSWORD=postgres
DB_HOST=localhost
DB_PORT=5432

# Allowed Hosts (comma-separated)
ALLOWED_HOSTS=localhost,127.0.0.1

# API Keys (update these with your own keys)
ANTHROPIC_API_KEY=your_anthropic_api_key_here
EOL

# 4. Update settings.py to use PostgreSQL
cat > config/settings.py << 'EOL'
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'critique',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'postgres'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
EOL

# 5. Update requirements.txt to include psycopg2-binary
if ! grep -q "psycopg2-binary" requirements.txt; then
    echo "psycopg2-binary>=2.9.0" >> requirements.txt
fi

# 6. Rename project references (if any exist in files)
find . -type f \( -name "*.py" -o -name "*.html" -o -name "*.md" -o -name "*.txt" \) ! -path "./venv/*" ! -path "./.git/*" | xargs sed -i '' "s/$TEMPLATE_NAME/$PROJECT_NAME/g" 2>/dev/null || true

# 7. Set up virtual environment
python3 -m venv venv
source venv/bin/activate

# Upgrade pip first to avoid installation issues
pip install --upgrade pip

# Install requirements
echo "Installing Python packages..."
pip install -r requirements.txt

# Verify psycopg2-binary is installed
if ! python -c "import psycopg2" 2>/dev/null; then
    echo "Warning: psycopg2-binary installation may have failed. Attempting to install directly..."
    pip install psycopg2-binary
fi

# 8. Set up git repository
rm -rf .git
git init
cat > .gitignore << EOL
# Django
*.log
*.pot
*.pyc
__pycache__/
local_settings.py
db.sqlite3
db.sqlite3-journal
media

# Python
*.py[cod]
*\$py.class
*.so
.Python
env/
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
*.egg-info/
.installed.cfg
*.egg

# Virtual Environment
venv/
ENV/

# Environment Variables
.env

# IDE files
.idea/
.vscode/
*.swp
*.swo

# macOS
.DS_Store

# Project specific
staticfiles/
EOL

git add .
git commit -m "Initial commit from Django template"

# 9. Final instructions
echo ""
echo "Project setup complete! Your new Django project '$PROJECT_NAME' is ready."
echo ""
echo "Next steps:"
echo "1. CD into your project: cd ../$PROJECT_NAME"
echo "2. Activate virtual environment: source venv/bin/activate"
echo "3. Create PostgreSQL database: createdb $PROJECT_NAME"
echo "4. Update .env file with your API keys if needed"
echo "5. Apply migrations: python manage.py migrate"
echo "6. Create superuser: python manage.py createsuperuser"
echo "7. Run development server: python manage.py runserver"
echo ""
echo "Happy coding!"

