# Generated by Django 6.0 on 2025-12-31 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('published_date', models.DateField()),
                ('linkedin_saves', models.IntegerField(default=0)),
                ('linkedin_comments', models.IntegerField(default=0)),
                ('linkedin_shares', models.IntegerField(default=0)),
                ('high_value_engagement', models.IntegerField(default=0, help_text='Comments from GS/Ambassador-level')),
                ('clarity_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Your retrospective clarity score (1-10)', null=True)),
                ('notes', models.TextField(blank=True, help_text='What worked, what failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='DraftCritique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('claude_critique', models.TextField(blank=True)),
                ('gpt_critique', models.TextField(blank=True)),
                ('gemini_critique', models.TextField(blank=True)),
                ('avg_clinical_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('consensus_verdict', models.CharField(blank=True, choices=[('CLEAR', 'Clear for Publication'), ('REVISE', 'Requires Revision'), ('REJECT', 'Structural Failure')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonaBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_title', models.CharField(help_text="e.g., 'Diplomatic Desk Officer, European Security'", max_length=200)),
                ('core_expertise', models.TextField(help_text='Areas of domain expertise')),
                ('writing_axioms', models.TextField(default='1. No emotional language\n2. Structural analysis only\n3. Minimize adjectives', help_text='Your non-negotiable writing principles')),
                ('target_audience', models.CharField(default='GS-level analysts, ambassadors, policy professionals', max_length=300)),
                ('forbidden_terms', models.TextField(default='excited, happy, honored, thrilled, blessed, passionate', help_text='Comma-separated banned words')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
