# Generated by Django 6.0 on 2026-01-01 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftRedraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_source', models.CharField(choices=[('claude', 'Claude'), ('gpt', 'GPT-4'), ('gemini', 'Gemini')], max_length=20)),
                ('redrafted_text', models.TextField()),
                ('original_clinical_score', models.IntegerField(blank=True, null=True)),
                ('redraft_clinical_score', models.IntegerField(blank=True, null=True)),
                ('improvement_delta', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_for_publication', models.BooleanField(default=False)),
                ('critique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redrafts', to='critique.draftcritique')),
            ],
            options={
                'ordering': ['-redraft_clinical_score'],
            },
        ),
    ]
