# Generated by Django 6.0 on 2026-01-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0002_draftredraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftredraft',
            name='redrafted_text',
        ),
        migrations.RemoveField(
            model_name='draftredraft',
            name='selected_for_publication',
        ),
    ]
