# Generated by Django 6.0 on 2026-01-02 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0003_remove_draftredraft_redrafted_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personabio',
            name='core_expertise',
            field=models.TextField(help_text='THE ENGINE: Areas of domain expertise (First Principles, Structural Physics)'),
        ),
        migrations.AlterField(
            model_name='personabio',
            name='forbidden_terms',
            field=models.TextField(default='excited, happy, honored, thrilled, blessed, passionate, amazing, incredible', help_text='THE ARMOR: Comma-separated banned words (Zero-Kelvin Shield)'),
        ),
        migrations.AlterField(
            model_name='personabio',
            name='target_audience',
            field=models.CharField(default='GS-level analysts, ambassadors, policy professionals', help_text='THE KINETIC: Target audience (Strategic Centrality - Thin Tail nodes)', max_length=300),
        ),
        migrations.AlterField(
            model_name='personabio',
            name='writing_axioms',
            field=models.TextField(default='1. Zero emotional language (Zero-Kelvin)\n2. Structural analysis only (Physics Engine)\n3. Verdicts, not opinions (The Weapon)\n4. Slightly venomous to mediocrity (Scalpel Edge)', help_text='THE WEAPON: Non-negotiable writing principles (High-Density Verdicts, Slightly Venomous)'),
        ),
        migrations.CreateModel(
            name='CommentGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True, help_text='LinkedIn post/comment URL (optional)')),
                ('source_text', models.TextField(help_text='The original post or comment text to respond to')),
                ('comment_option_1', models.TextField(help_text='First comment option (analytical angle)')),
                ('comment_option_2', models.TextField(help_text='Second comment option (framework angle)')),
                ('comment_option_3', models.TextField(help_text='Third comment option (counterpoint angle)')),
                ('selected_option', models.IntegerField(blank=True, choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3')], help_text='Which option the user selected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DraftRedraft',
        ),
    ]
