# Generated by Django 6.0 on 2026-01-04 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0004_alter_personabio_core_expertise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='draftcritique',
            name='artifact',
            field=models.TextField(blank=True, help_text='Third Object (framework/matrix) suggested by LLM'),
        ),
        migrations.AddField(
            model_name='draftcritique',
            name='forbidden_alternatives',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='draftcritique',
            name='historical_avg_clinical_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Average clinical tone score computed from top archived posts', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='draftcritique',
            name='sentence_triggers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='draftcritique',
            name='avg_clinical_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='draftcritique',
            name='consensus_verdict',
            field=models.CharField(blank=True, choices=[('PROCESSING', 'Processing'), ('CLEAR', 'Clear for Publication'), ('REVISE', 'Requires Revision'), ('REJECT', 'Structural Failure')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='commentgeneration',
            index=models.Index(fields=['user', 'created_at'], name='critique_co_user_id_f07aae_idx'),
        ),
        migrations.AddIndex(
            model_name='commentgeneration',
            index=models.Index(fields=['created_at'], name='critique_co_created_58d411_idx'),
        ),
        migrations.AddIndex(
            model_name='draftcritique',
            index=models.Index(fields=['user', 'submitted_at'], name='critique_dr_user_id_9dd8f5_idx'),
        ),
        migrations.AddIndex(
            model_name='draftcritique',
            index=models.Index(fields=['submitted_at'], name='critique_dr_submitt_da999f_idx'),
        ),
    ]
